name: Scan for Secrets
on: [push, pull_request]

jobs:
  call-secret-scan:
    uses: pharmeasy/Github-Secret-Scanning/.github/workflows/central_secretScanning_infosec.yaml@main
    secrets: 
      JIRA_URL: ${{ secrets.JIRA_URL }}  
      JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}  
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    